# ***Python for ML/DL***
---

<center>
<img src="https://ehackz.com/wp-content/uploads/2018/02/Python.jpg" height = "40%" width = "60%">

## **Introduction PEP8**

<center>
<img src="https://d2o2utebsixu4k.cloudfront.net/media/images/1a38e5b6-4815-4390-ad92-a52b825fba0b.jpg" height="70%" width="80%">

## What is PEP8?

[PEP 8](https://realpython.com/python-pep8/) (Python Enhancement Proposals), sometimes spelled PEP8 or PEP-8, is a document that provides guidelines and best practices on how to write Python code. It was written in 2001 by Guido van Rossum, Barry Warsaw, and Nick Coghlan. The primary focus of PEP 8 is to improve the readability and consistency of Python code.

### **Naming Conventions**

When you write Python code, you will avoid the inappropriate variables names . Choosing  names will save you time and you’ll be able to figure out, from the name, what a certain variable, function, or class represents.

### **Sytels**

**Function**: Use a word or words in lowercase and separate with underscore.

**Variable**: Use a lowercase single letter, word, or words. Separate words with underscores.

**Class**: Use upper in the first letter and don't separate the words with underscore.

**methods**: Use a lowercase word or words and separete with underscores.

**Constant**: Use an uppercase single letter, word, or words. Separate words with underscores

**Module**: Use lowercase word or words  with underscores.

**package**: Use lowercase and do not underscores.

**Variable**

In [7]:
full_name = "Juan Perez"
name, surname = full_name.split()

print(name, surname)

Juan Perez


## **Constant**

In [32]:
NAME_MOVIL_PHONE = [
    'Samsung',
    'Huaweii',
    'Nokia',
    'Claro'
]

NAME_MOVIL_PHONE

['Samsung', 'Huaweii', 'Nokia', 'Claro']

## **Function**

In [46]:
def random_choise():
    return None

## **Class**

In [44]:
class MovilPhone():
    pass

### **Code Layout**

We also learn about indentation because it is very important to make your code more readable. Here you will learn how to handle the PEP8 recommended limit of 79 lines of characters.
Surround top-level functions and classes with two blank lines. 

In [54]:
class FirstClass():
    pass


class SecondClass():
    pass


def top_level_function():
    return None

Surround method definitions inside classes with a single blank line.

In [55]:
class MovilPhone():
    
    def __init__(self):
        return None

    def __str__(self):
        return None

Use blank lines sparingly inside functions to show clear steps.

In [52]:
import numpy as np


def normalization(name_array):

    mean = np.median(name_array)

    std = np.std(name_array)

    return (name_array - mean) / std

## **Maximum Line Length and Line Breaking**

PEP 8 suggests lines should be limited to 79 characters. This is because it allows you to have multiple files open next to one another, while also avoiding line wrapping.

In [56]:
def function(arg_1, arg_2, 
             arg_3, arg_4):
    return None

In [3]:
from torch import (nn, 
                   functional, 
                   cuda, 
                   onnx)

If line breaking needs to occur around binary operators, like + and *, it should occur before the operator. This rule stems from mathematics. Mathematicians agree that breaking before binary operators improves readability. 

In [69]:
lamda =  0.01

size = 50

weight_sum = 0.956 

regularization = (lamda 
            * weight_sum 
            / size)

## **Indentation Following Line Breaks**

When you’re using line continuations to keep lines to under 79 characters, it is useful to use indentation to improve readability. It allows the reader to distinguish between two lines of code and a single line of code that spans two lines.

In [ ]:
'''
while (flag==True or 
       count<200):
       print(count)
       -----
'''

In [64]:
flag = True

count = 0

while (flag and 
              count<5):
       count +=1

In [ ]:
flag = True

count = 0

while (flag==True and 
       count<5):
       #Here initialize the code
       count +=1

## **hanging indent**

In [70]:
def function(
        arg_1, arg_2,
        arg_3, arg_4):
    return None

In [72]:
var = function(
    1, 2,
    3, 4)


## **Closing Brace**

Line up the closing brace with the first non-whitespace character of the previous line:

In [73]:
prime = [
    2, 3, 5,
    7, 11, 13
    ]

Line up the closing brace with the first character of the line that starts the construct:

In [74]:
prime = [
    2, 3, 5,
    7, 11, 13
]

## **Block Comments**

They are useful when you have to write several lines of code to perform a single action, such as importing data from a file or updating a database entry. They are important as they help others understand the purpose and functionality of a given code block.

- Indent block comments to the same level as the code they describe.
- Start each line with a # followed by a single space.
- Separate paragraphs by a line containing a single #.



In [4]:
x = "John Smith"  # Student Name

empty_list = []  # Initialize empty list

x = 5  # This is an inline comment
x = x * 5  # Multiply x by 5

## **Documentation Strings**


Documentation strings, or docstrings, are strings enclosed in double (""") or single (''') quotation marks that appear on the first line of any function, class, method, or module. 

The most important rules applying to docstrings are the following:

Surround docstrings with three double quotes on either side, as in """This is a docstring""".

Write them for all public modules, functions, classes, and methods.

Put the """ that ends a multiline docstring on a line by itself

In [2]:
import torch.nn as nn
import torch.nn.functional as F


class Model(nn.Module):
    """This  is an subclass of super class nn.Module
    To create a subclass, you need implements the folowing two methods.
       --<__init__>: initialize the class; this module call the super(Model, self).__init__()
       --<forward>: produce intermediate results.
    """

    def __init__(self, opt):
        """Initialize the Model class
        Parameters:
            opt (option )-- pass a dictionary with the hypeparameters.
            when implements this class
            -- self.device (str): specify the device type.
            -- self.epoch (int): define the epoch.
            -- self.conv1 (torch.nn.modules.conv.Conv2d):  define the first conv2d
            -- self.conv2 (torch.nn.modules.conv.Conv2d): define the second conv2d
        """
        super(Model, self).__init__()
        self.device = opt["gpu_is"]
        self.epoch = opt["epoch"]
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        """Run forward pass"""
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))


## **Whitespace Around Binary Operators**

urround the following binary operators with a single space on either side:

- Assignment operators (=, +=, -=, and so forth)

- Comparisons (==, !=, >, <. >=, <=) and (is, is not, in, not in)

- Booleans (and, not, or)

In [77]:
def function(default_parameter = 5):
    pass

In [1]:
x = 1

y = x**4 + x**3 + x**2 + x + 0.1

z = (x+y)**2 * (y-x)**3

In [80]:
if x>5 and x%2==0:
    print('x is larger than 5 and divisible by 2!')

In [84]:
list_ = [1, 2, 4, 6, 7, 8]

list_[3:5]

# Treat the colon as the operator with lowest priority
list_[z+1 : z+2]

# In an extended slice, both colons must be
# surrounded by the same amount of whitespace
list_[3:4:5]
list_[z+1 : x+2 : x+3]

# The space is omitted if a slice parameter is omitted
list_[z+1 : z+2 :]

print("")

## **When to Avoid Adding Whitespace**

The most important place to avoid adding whitespace is at the end of a line. This is known as trailing whitespace. It is invisible and can produce errors that are difficult to trace.



In [ ]:
list_ = [1, 2, 4, 6, 7, 8]


In [ ]:
print(x, y)

- list_\[1]

- tuple_ = (1,)

In [88]:
var1 = 5
var2 = 6
some_long_var = 7

In [90]:
my_bool = True

if my_bool:
    print('6 is bigger than 5')

6 is bigger than 5


## **Online**

---

You so availble in the internet PEP8's corrector with for example:

- [PEP8 Online](http://pep8online.com/)  
- [PythonChecker](https://www.pythonchecker.com/)

## **Formatters**

- [Black](https://pypi.org/project/black/): **pip install black**

Black is the uncompromising Python code formatter. By using it, you agree to cede   control over minutiae of hand-formatting. In return, Black gives you speed,                  determinism, and freedom from pycodestyle nagging about formatting. You will save            time and mental energy for more important matters.

# **Exception**

So far the error messages have barely been mentioned, but if you've tried the examples above you've probably seen a few. There are (at least) two different types of errors: syntax errors and exceptions. 

## **Sintaxis Errors**

Syntax errors are the most common when we start programming

In [194]:
flag = True

if flag print("Good")

SyntaxError: invalid syntax (<ipython-input-194-8a581e9adad3>, line 3)

## **Exception**

Even if a statement or expression is syntactically correct, it can generate an error when it is attempted to execute. Errors detected during execution are called exceptions

In [195]:
1 / 0

ZeroDivisionError: division by zero

## **Try-except**

The [try](https://docs.python.org/es/3/tutorial/errors.html) statement works as follows:

First, the try clause (the line (s) between the try and the except keywords) is executed.

If no exceptions occur, the except clause is ignored and the execution of the try clause ends.

If an exception occurs during the execution of the try clause the rest of the clause is ignored. So if the exception type matches the exception listed after the except, the except clause executes, and execution continues after the try.

In [84]:
denominator = int(input("Give me a number"))

numerator = int(input("Give me a number"))

try:
    print(numerator / denominator)
except ZeroDivisionError:
    print("Error!!!")

4.0


In [1]:
while True:
    try:
        denominator = int(input("Give me a number"))

        numerator = int(input("Give me a number"))
        break
    except ValueError:
        print("Error!!!")

try:
    print(numerator / denominator)
except ZeroDivisionError:
    print("Error!!! :c")

Error!!! :c


## **File**

In [32]:
try:
    f = open('myfile.txt')
    f.close()
except FileNotFoundError as err:
    print("{}: {}".format(FileNotFoundError,err))
except ValueError:
    print("Could not convert data to an integer.")

<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'myfile.txt'


## **Raise**

The raise statement allows the programmer to force a specific exception to occur.

In [61]:
while True:
    try:
        denominator = int(input("Give me a number"))

        numerator = int(input("Give me a number"))

        print(numerator / denominator)
        
        break
    except (ZeroDivisionError, ValueError):
        print("Error!!!")
        raise ZeroDivisionError("denominator mustn't zero")

Error!!!


ZeroDivisionError: denominator mustn't zero

In [87]:
try:
    input_ = int(input("give a number"))
except ValueError as err:
    print("ValueError: {}".format(err))
finally:
    print("print first")

ValueError: invalid literal for int() with base 10: 'f'
print first


## **MyException**

In [26]:
class ValidationError(Exception):
    """
    This class inheritance of Exception Class
    Arguments:
        --self.errors: Exception happened
        --self.message: Message personality
    Methods:
        --<__init__>: Contstructor of the class
        --<__str__>: Special Method
    """

    def __init__(self, message, errors):
        super(ValidationError, self).__init__(message)
        self.errors = errors
        self.message = message

    def __str__(self):
        return f"{self.message}..."


try:

    denominator = int(input("Give me a number"))
    raise ValidationError("Error", ZeroDivisionError)
except ValueError:
    raise ValidationError("You don't write strings", ValueError)

ValidationError: You don't write strings...

# **Numpy**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

<center>
<img src="https://techscript24.com/wp-content/uploads/2020/10/86498201-a8bd8680-bd39-11ea-9d08-66b610a8dc01.png" width="20% height="30%">


**[Install Numpy](https://numpy.org/install/)**

pip install numpy

**Import numpy**

In [89]:
import numpy as np

## Initialize Numpy's array

Convert a list in **Numpy** array

## Array

In [71]:
numpy_array_example_1 = np.array([[1, 3, 4, 5]])#(1,4)
#create a NumPy array is to create it from a Python list
print(
    "array:{}\n\n type: {}".format(numpy_array_example_1, type(numpy_array_example_1))
)

array:[[1 3 4 5]]

 type: <class 'numpy.ndarray'>


## **Zeros**

In [91]:
numpy_array_zeros = np.zeros((2,4)) #Create a Numpy's arrys of zeros with shape (2, 4)

numpy_array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## **full**

In [94]:
numpy_array_full = np.full((1,4), 3) #Create a Numpy's array of 8s with shape (1, 4)

numpy_array_full

array([[3, 3, 3, 3]])

## **Extra examples**

In [97]:
numpy_array_example_2 = np.array([[1, 3, 4, "hello"]], dtype=np.str)

print(
    "array:{}\n\n type: {}".format(numpy_array_example_2, type(numpy_array_example_2))
)

array:[['1' '3' '4' 'hello']]

 type: <class 'numpy.ndarray'>


In [68]:
numpy_array_example_3 = np.array([[1, 3, 4, 3.4]])

print(
    "array:{}\n\n type: {}".format(numpy_array_example_3, type(numpy_array_example_3))
)

array:[[1.  3.  4.  3.4]]

 type: <class 'numpy.ndarray'>


## **dtype**

In [99]:
numpy_array_example_3.dtype  #Data-type of the array’s elements.

dtype('float64')

## **Shape**

In [102]:
numpy_array_example_1.shape 
#The shape of an array is the number of elements in each dimension.

(1, 4)

## **ndim**

In [103]:
numpy_array_example_2.ndim #Number of array dimensions. 

2

## **size**

In [60]:
numpy_array_example_1.size #Size of the first dimension of numpy.ndarray: len()[[1, 3, 4, 5]]

4

## **itemsize**

In [105]:
numpy_array_example_3.itemsize #Length of one array element in bytes.

8

## **Array index**

In [51]:
list1 = [1,2,3,4,5]

list2 = [6,7,8,9,0]

list_arrays_2 = np.array([list1,list2])

print(f"{r2}\n") # Numpy's array with shape (2, 5)

'''
[[1 2 3 4 5]
[6 7 8 9 0]]
'''

print(f"{r2[1, 3]}\n")

print(f"{r2[0, 4]}\n")

print(f"{r2[1]}")

[[1 2 3 4 5]
 [6 7 8 9 0]]

9

5

[6 7 8 9 0]


## **Boolean Indexing**

In [44]:
print(numpy_array_example_1 < numpy_array_full)

## numpy_array_example_1 : [[1 3 4 5]]  < numpy_array_full: [[8., 8., 8., 8.]]


[[ True  True  True  True]]


## **full_like**

In [106]:
list_array_index_1 = np.array([[1, 4, 3, 8, 9, 12]]) #Initilize Numpy' array (1, 7)

list_array_full_like = np.full_like(list_array_index_1, np.mean(list_array_index_1))

print(list_array_full_like)

list_array_index_1[list_array_full_like < list_array_index_1 ]

[[6 6 6 6 6 6]]


array([ 8,  9, 12])

## **Slicing Arrays**

In [73]:
array_list_example = np.array(
    [[1,2,3,4,5],
    [4,5,6,7,8],
    [9,8,7,6,5]])

print(f"{array_list_example[0, :-1]}\n")

print(f"{array_list_example[1, ::-1]}\n")

print(f"{array_list_example[2, 1:4]}\n")

[1 2 3 4]

[8 7 6 5 4]

[8 7 6]



In [63]:
print(f"{array_list_example[2, :-1]}\n")

print(f"{array_list_example[1, -4:-1]}\n")

[9 8 7 6]

[5 6 7]



## **Operation with Numpy**
---



### **Sum**

In [5]:
list_1 = [1, 2, 4, 5]  #Initialize a python's list

list_2 = [1, 5, 5, 4]  #Initialize a python's list 

In [7]:
list_array_1 = np.array([[1, 2, 4, 5]])  #Initialize a numpy array shape (1, 4)

list_array_2 = np.array([[1, 3, 5, 6]])  #Initialize a numpy array shape (1, 4)

**Compare**

In [79]:
print(list_1 + list_2)  #The list_2 is adding at the final of list_1

[1, 2, 4, 5, 1, 5, 5, 4]


In [78]:
print(list_array_1 + list_array_2)  #Don't forget arrays' sum with (1, 4) + (1, 4) -> (1, 4)

[[ 2  5  9 11]]


## Broadcasting
---

In [80]:
list_array_1 + 4  #Rember the shape for the list_array_1 ->(1,4) and the list is:[1, 2, 4, 5]

array([[5, 6, 8, 9]])

In [8]:
list_array_3 = [[1, 3, 4, 5], [1, 4, 5, 6]]  # Initialize a python's list  two sublist

list_array_3 = np.array(list_array_3) #Convert the list in Numpy's array with shape -> (2, 4)

list_array_2 + list_array_3  #Sum two Numpy arrays' with shape: (1, 4) + (2, 4) -> (2, 4)

array([[ 2,  6,  9, 11],
       [ 2,  7, 10, 12]])

In [9]:
list_array_4 =  [[1, 3, 4, 5]]  #Initialize a python's list (1, 4) 

list_array_4 = np.array(list_array_4) #Actualize the list_array_4 shape: (1, 4)

list_array_4 + list_array_2.T #shape (1, 4) + (4, 1) -> (4, 4)

array([[ 2,  4,  5,  6],
       [ 4,  6,  7,  8],
       [ 6,  8,  9, 10],
       [ 7,  9, 10, 11]])

Is it possible? What is the shape of this?

list_array_4 + list_array_3.T #shape (1, 4) + (4, 2) -> ?

**Division**

In [2]:
list_array_5 = np.random.randn(2, 6) #Initialize numpy's array 

list_array_6 = np.random.randn(1,6) #Initialize numpy's array

In [123]:
list_array_5 / 3 #Divide with three

array([[ 0.08880278, -0.15692396,  0.50227734,  0.75372394, -0.10482422,
        -0.09868096],
       [-0.0394082 ,  0.03715227, -0.12289026,  0.00133819,  0.38420478,
        -0.16264112]])

In [113]:
list_array_6 / list_array_5 # Divide (1, 6) / (2, 6) -> (2, 6)

array([[ -2.23436106,  -5.16067012,  -0.20325389,  -0.05027103,
          1.08418275,   1.68437749],
       [  5.03492905,  21.79766721,   0.83073972, -28.31463808,
         -0.29580217,   1.02198009]])

In [117]:
list_array_4 / list_array_6.T #Divede (1, 4) / (6, 1) -> (6, 4)

array([[ -1.6799595 ,  -5.0398785 ,  -6.71983801,  -8.39979751],
       [  0.41160759,   1.23482277,   1.64643036,   2.05803795],
       [ -3.26509852,  -9.79529557, -13.06039409, -16.32549262],
       [ -8.79728437, -26.39185312, -35.18913749, -43.98642186],
       [ -2.93301735,  -8.79905204, -11.73206939, -14.66508673],
       [ -2.00542277,  -6.01626831,  -8.02169108, -10.02711386]])

Is it possible?  What is the shape of this?

- list_array_4 / list_array_6 #shape (1, 4) / (1, 6) -> ?

- shape (2, 5) / (3, 1) -> ?

## **Vectorization**

In [115]:
import math

math_sigmoid = lambda x: 1 / (1 + math.exp(-x))

numpy_sigmoid = lambda x : 1 / (1 + np.exp(-x)) 

In [116]:
import time

In [117]:
vector_example_1 = np.random.rand(1, 1000)  #Create a Numpy's array (1, 1000)

In [119]:
#Calculete math_sigmoid 

auxiliar_array = np.empty(vector_example_1.shape[1])

time_start = time.time()

for ix in range(vector_example_1.shape[1]):
    auxiliar_array[ix] = math_sigmoid(vector_example_1[0][ix])

time_finish = time.time()

In [120]:
print(time_finish-time_start) #Time of Numpy's array

0.002669095993041992


### **Compare**

In [122]:
time_start = time.time()

numpy_sigmoid(vector_example_1) #Use Numpy for calculate the sigmoid function 

time_finish = time.time()

In [123]:
print(time_finish-time_start) #Time of numpy_sigmoid

0.001688241958618164


## **Other Example**

In [21]:
x = np.random.randn(2, 6) #Return Numpy's array with (2, 6)

polynomic = lambda x: x**3 + 2*x**2 + 4

"""
Argument: 
    - x: This is a Numpy's array with (n, m)
return :
    - x^3 + 2*x^2 + 4
"""

print(polynomic(x))

[[ 7.93645266  4.31180062  4.0724336   4.7399741   4.97927025  4.22316028]
 [ 4.96712777 10.83470582  4.95801662  5.16009007  4.18223685  4.05740096]]


### **Dot**

In [ ]:
"""
np.dot is the dot product of two matrices.

|A B| . |E F| = |A*E+B*G A*F+B*H|
|C D|   |G H|   |C*E+D*G C*F+D*H|

"""

In [124]:
def initilize_parameters(n_h, n_x, n_y):
    """
    Argument:
        n_x: size input layer
        n_h: size hidden layer
        n_y: size output layer
    return:
        Dictionary with paramaters:
        W1:  Weight matrix of (n_h, n_x)
        b1: bias vector of (n_h, 1)
        W1:  Weight matrix of (n_y, n_h)
        b2: bias vector of (n_y, 1)
    """
    W1 = np.random.randn(n_h, n_x)
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y,n_h)
    b2 = np.zeros((n_y, 1))
    
    parameters = {
        'W1': W1,
        'W2': W2,
        'b1': b1,
        'b2': b2
    }
    return parameters

In [126]:
def forward(parameters, A):
     """
     Implements the forwardpass 
     Arguments:
        -- parameters: This is a dictionary with the weights and bias.
        --- A is matrix intput size (n_x, n_examples)
     return:
        -- A2 -> return activation function
     """

     W1, b1, W2, b2 = parameters["W1"], parameters["b1"], parameters["W2"], parameters["b2"]

     sigmoid = lambda x: 1/(1+np.e**(-x)) #define function labmda with sigmoid operation
    
     A1 = np.dot(W1,A) + b1 # apply the np.dot (n_h, n_x) , (n_x, n_examples) + (n_h, 1)-> ?
     print(A1.shape)
     A1 = sigmoid(A1)  #Apply the sigmoid function  shape ??
     print(A1.shape)
     A2 = np.dot(W2,A1) + b2 # apply the np.dot  (n_y, n_h)
     print(A2.shape)
     A2 = sigmoid(A2) #Apply the sigmoid function  shape ??
     print(A2.shape) 
     return A2

parameters = initilize_parameters(3, 3, 2)

A = np.random.rand(3, 4)

forward(parameters,A)

(3, 4)
(3, 4)
(2, 4)
(2, 4)


array([[0.5951272 , 0.59314427, 0.60740386, 0.64156711],
       [0.73124907, 0.7194176 , 0.735907  , 0.84385565]])

## **Multiply**

In [ ]:
"""
Multiply

|A B| ⊙ |E F| = |A*E B*F|
|C D|   |G H|   |C*G D*H|
"""

### **Don't forget**
- Original array -> (5, 3)
- Example_1 return an array (1,1) 
- Example_2 return a scalar (1,) 
- Example_3 return an array ->  (5, 1)
- Example_4 lose a dim -> (5,)
- Example_5 return an array -> (3,1)
- Example_6 lose a dim (3,)

In [106]:
a = np.array([[0, 0, 0],
              [0, 1, 0],
              [0, 2, 0],
              [1, 0, 0],
              [1, 1, 0]]) #Initialize a Numpy's array (5, 3)

np.sum(a, keepdims=True) #Example_1 :array([[6]]) (1,1)

np.sum(a, keepdims=False)  # Example_2: 6 -<

np.sum(a, axis=1, keepdims=True) #Example_3: array([[0], [1], [2], [1], [2]])

np.sum(a, axis=1, keepdims=False) #Example_4: array([0, 1, 2, 1, 2])

np.sum(a, axis=0, keepdims=True) #Example_5: array([[2, 4, 0]])

np.sum(a, axis=0, keepdims=False) #Example_6: array([2, 4, 0])


<class 'numpy.int64'>


### **[Crossentropy](https://ml-cheatsheet.readthedocs.io/en/latest/loss_functions.html)**

<center>
<img src="https://gombru.github.io/assets/cross_entropy_loss/intro.png" width="90%" height="100%">

In [94]:
Y = np.array([[0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1]])

Y_hat = np.array(
    [
        [0.01, 0.005, 0.8, 0.005],
        [0.01, 0.08, 0.01, 0.9],
        [0.9, 0.01, 0.02, 0.07],
        [0.001, 0.001, 0.08, 0.9],
    ]
)


def crossentropy(Y, Y_hat):
    """
    Arguments:
        -- Y : (ndarrray) This is Numpy's array with (n, m)
        -- Y_hat : (ndarray)  This is Numpy's array with (n,m)
    return:
        - n: length of Numpy's array
        - (-1/n)*(sum(Y*log(Y_hat) +  (1-Y)*log(1-Y_Hat) ) 
    """
    n = len(Y)
    return (-1 / n) * np.sum(
        np.multiply(Y, np.log(Y_hat)) + np.multiply((1 - Y), np.log(1 - Y_hat)), axis=1, keepdims=True)


loss = crossentropy(Y, Y_hat)

print(loss)


[[0.06080474]
 [0.0522107 ]
 [0.05204606]
 [0.04768578]]


## **Aplication**

## **Softmax**

<center>
<img src="https://i.ytimg.com/vi/lvNdl7yg4Pg/maxresdefault.jpg" width="60%" height="70%">

In [4]:
import numpy as np

softmax = lambda x: np.e**(x)/np.sum(np.e**(x), keepdims=True, axis=1)
    """the function lambda calculate a softmax function
        args:
            - x: (ndarry) this is the Numpy's array of shape (n, m)
        return:
           - Numpy's array with shape (n, m)
    """
softmax(list_array_5)

array([[0.15757634, 0.06022352, 0.04688021, 0.32244898, 0.13388508,
        0.27898587],
       [0.11440411, 0.07216296, 0.31916992, 0.06257798, 0.0434761 ,
        0.38820893]])

## **Tanh**

<center>
<img src="https://paperswithcode.com/media/methods/Screen_Shot_2020-05-27_at_4.23.22_PM_dcuMBJl.png" width="40%" height="50%">

In [7]:
tanh = lambda x: (np.e**(x)-np.e**(-x))/(np.e**(-x)+np.e**(x))

"""the function lambda calculate a tanh activation function
        args:
            - x: (ndarry) this is the Numpy's array of shape (n, m)
        return:
           - Numpy's array with shape (n, m)
"""

tanh(list_array_5)

array([[ 0.52157276, -0.36561261, -0.56067462,  0.86030904,  0.39319153,
         0.81767087],
       [ 0.01621423, -0.41744553,  0.77875623, -0.52781239, -0.74037559,
         0.8448906 ]])

In [8]:
relu = lambda x: np.maximum(0, x)
relu(list_array_5)

array([[0.57849782, 0.        , 0.        , 1.29453269, 0.41556963,
        1.14974889],
       [0.01621565, 0.        , 1.04220226, 0.        , 0.        ,
        1.23802229]])

## **Copy**

In [138]:
list1 = [[1,2,3,4], [5,6,7,8]] # Creat a list of Python
array_1 = np.array(list1)  # Create a Numpy's array
print(array_1)

[[1 2 3 4]
 [5 6 7 8]]


In [139]:
array_2 = array_1 # creates a copy by reference
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [143]:
array_2[0, 2] = 4 # Change the value array[0, 2]: 3 (Initial Value) for 4 

print(f"array_1:\n {array_1} \n\narry_2:\n {array_2}")

array_1:
 [[1 2 4 4]
 [5 6 7 8]] 

arry_2:
 [[1 2 4 4]
 [5 6 7 8]]


In [146]:
array_3 = array_1.copy() #Copy the array_1 in array_3

array_1[0, 2] = 3

array_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
array_3

array([[1, 2, 4, 4],
       [5, 6, 7, 8]])

## **Reshaping Arrays** 

## **Reshape**

In [11]:
list_array = np.random.random((2, 8)) # array with (2, 8)

list_array

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251, 0.15579619,
        0.32155267, 0.09749826, 0.97946898],
       [0.65984486, 0.77965445, 0.06128539, 0.66572453, 0.24093297,
        0.06242658, 0.33610954, 0.54171027]])

In [12]:
list_array.reshape(4, 4) ## array shape (4, 4)

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251],
       [0.15579619, 0.32155267, 0.09749826, 0.97946898],
       [0.65984486, 0.77965445, 0.06128539, 0.66572453],
       [0.24093297, 0.06242658, 0.33610954, 0.54171027]])

In [13]:
list_array.reshape(1,16) #array shape (1, 16)

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251, 0.15579619,
        0.32155267, 0.09749826, 0.97946898, 0.65984486, 0.77965445,
        0.06128539, 0.66572453, 0.24093297, 0.06242658, 0.33610954,
        0.54171027]])

In [14]:
list_array.reshape(4,-1) #reshape dicede the column

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251],
       [0.15579619, 0.32155267, 0.09749826, 0.97946898],
       [0.65984486, 0.77965445, 0.06128539, 0.66572453],
       [0.24093297, 0.06242658, 0.33610954, 0.54171027]])

In [15]:
list_array.reshape(-1, 2) # reshape decida the row

array([[0.48313128, 0.97117467],
       [0.9343399 , 0.51077251],
       [0.15579619, 0.32155267],
       [0.09749826, 0.97946898],
       [0.65984486, 0.77965445],
       [0.06128539, 0.66572453],
       [0.24093297, 0.06242658],
       [0.33610954, 0.54171027]])

In [16]:
list_array ## Keep the orignal shape

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251, 0.15579619,
        0.32155267, 0.09749826, 0.97946898],
       [0.65984486, 0.77965445, 0.06128539, 0.66572453, 0.24093297,
        0.06242658, 0.33610954, 0.54171027]])

## **[Resize](https://numpy.org/doc/stable/reference/generated/numpy.resize.html)**

In [18]:
list_array #Numpy array -> (2, 8) 

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251, 0.15579619,
        0.32155267, 0.09749826, 0.97946898],
       [0.65984486, 0.77965445, 0.06128539, 0.66572453, 0.24093297,
        0.06242658, 0.33610954, 0.54171027]])

In [19]:
list_array.resize(4, 4) # change (2, 8) -> (4, 4)

In [20]:
list_array # Numpy's array (4, 4)

array([[0.48313128, 0.97117467, 0.9343399 , 0.51077251],
       [0.15579619, 0.32155267, 0.09749826, 0.97946898],
       [0.65984486, 0.77965445, 0.06128539, 0.66572453],
       [0.24093297, 0.06242658, 0.33610954, 0.54171027]])