In [1]:
#!pip install transformers

In [3]:
from transformers import AutoTokenizer

In [4]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [5]:
raw_inputs = ["Hello world, first notebook of trnasformers library", "Hello HuggingFace"]
inputs = tokenizer(raw_inputs, padding= True, truncation= True, return_tensors='pt') #np, tf

TypeError: 'DistilBertTokenizer' object is not callable

In [45]:
print(inputs)

{'input_ids': tensor([[  101,  7592,  2088,  1010,  2034, 14960,  1997, 19817, 11649, 14192,
          2545,  3075,   102],
        [  101,  7592, 17662, 12172,   102,     0,     0,     0,     0,     0,
             0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [35]:
print(type(inputs['input_ids']))

<class 'torch.Tensor'>


In [36]:
## Automodel class loads a model without its pretraining head
from transformers import AutoModel

model = AutoModel.from_pretrained(checkpoint)
outputs = model(**inputs)
print(outputs.last_hidden_state.shape) 

torch.Size([2, 13, 768])


In [37]:
print(outputs.last_hidden_state)

tensor([[[ 0.2799,  0.2040,  0.5526,  ...,  0.3099,  0.5885, -0.1467],
         [ 0.5097,  0.4891,  0.6593,  ...,  0.1550,  0.6896, -0.2446],
         [ 0.3101,  0.4378,  1.0673,  ...,  0.1617,  0.6083, -0.1961],
         ...,
         [-0.3140,  0.3753,  0.7833,  ...,  0.0231,  0.5293,  0.3230],
         [ 0.6525,  0.3583,  1.1043,  ..., -0.0208,  0.1155,  0.2565],
         [ 1.3960,  0.2308,  0.3350,  ...,  0.7951, -0.0729, -0.3733]],

        [[ 0.1246,  0.2134,  0.7362,  ...,  0.4880,  1.0364, -0.2482],
         [ 0.5319,  0.5746,  0.8990,  ...,  0.3442,  0.9985, -0.3179],
         [ 0.2423,  0.5646,  1.4805,  ...,  0.4333,  0.5820, -0.0133],
         ...,
         [-0.0974,  0.1596,  0.6912,  ...,  0.7958,  0.9439,  0.0754],
         [-0.1998,  0.1480,  0.6810,  ...,  0.7745,  0.8997,  0.0937],
         [-0.2237,  0.0871,  0.6939,  ...,  0.8361,  0.8664,  0.0524]]],
       grad_fn=<NativeLayerNormBackward>)


In [38]:
# to classification task call AutoModelForSequenceClassification loads a model with 
# classification head
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(**inputs)
print(outputs.logits) # 2 x 2 , 2 sentences and 2 possible label

tensor([[-3.6532,  3.8036],
        [-3.1625,  3.4260]], grad_fn=<AddmmBackward>)


In [40]:
import torch
predictions =  torch.nn.functional.softmax(outputs.logits, dim = -1)
print(predictions)

tensor([[5.7714e-04, 9.9942e-01],
        [1.3741e-03, 9.9863e-01]], grad_fn=<SoftmaxBackward>)


In [41]:
print(model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}
